export const intro = "Guardos.eu employs various technologies such as cookies, trackers and scripts (hereinafter collectively referred to as 'Technologies') across its websites and applications to enhance user experience in terms of speed, security, and overall performance. These Technologies are implemented not only directly by Guardos.eu but also through third-party services engaged by Guardos.eu. Ensuring your privacy concerning these Technologies is of paramount importance to us. For detailed insights into how we handle your data, please consult our ";
export const intro2 = "Through this cookie statement, we aim to elucidate the nature and purpose of the Technologies we utilize. Should you have any inquiries regarding our use of Technologies or concerns about your privacy in relation to these Technologies, feel free to reach out to us at guardos-help@outlook.com.";
export const intro3 = "Upon your initial visit to our websites and applications from any device (such as a computer, smartphone, or tablet), you will encounter our cookie banner. Here, you have the option to either accept all cookies or customize your cookie settings. You retain the flexibility to adjust your cookie preferences at any time through the preferences center (provided below). Nonetheless, please be aware that disabling certain types of cookies may impact your browsing experience on our websites and applications, as well as the range of services we can offer. Rest assured, we always set cookies to remember your preferences and other essential technical cookies.";

export const cookies = "We only store essential cookies, including those with limited analytical functionality, on your device if they are crucial for the proper operation of our services. However, for all other categories of cookies, we seek your explicit consent based on their respective purposes and functions. It's important to note that certain cookies may be placed by third-party services featured on our pages. For a comprehensive understanding of all the technologies we employ, along with their purposes, functions, and lifespan, please refer to our regularly updated " 
export const cookies2 = "This ensures that you have an accurate overview of the technologies utilized by us.";

export const introTech = "As previously stated, Guardos.eu employs various Technologies for data collection. The Technologies utilized by Guardos.eu include scripts, trackers, and cookies. Below, we will provide an explanation of each Technology:";

export const script = "A script is a segment of programming code designed to facilitate the proper functioning and interactivity of our website. This code may be executed either on our server or directly on your device. Its primary purpose is to ensure seamless operation and enhance user engagement by enabling interactive features and dynamic content presentation.";
export const tracker = "A tracker is an inconspicuous element, often a tiny snippet of text or an image embedded within our website, utilized to monitor and analyze website traffic. To effectively map traffic patterns, we employ multiple trackers, each designed to capture various types of data about user interactions. Additionally, third-party entities may be authorized to install trackers on our website to assist in monitoring and analyzing traffic on our behalf. These trackers play a crucial role in providing valuable insights into user behavior and optimizing our website's performance and user experience.";
export const cookie = "A cookie is a basic, compact text file that is transmitted from certain pages of our website and subsequently stored by your web browser on your computer's hard drive. While some cookies serve to establish connections between your activities on our website during your visit, others persist on your computer's hard drive and are relayed back to our servers, or those of third parties who have deployed the cookie on our behalf, when you revisit our website. This enables us to recognize your device and tailor your browsing experience accordingly, whether it involves remembering your preferences or providing personalized content.";

export const purposeTech = "We deploy cookies, trackers, and scripts for distinct purposes: functional, analytical, and marketing objectives. Here's an outline of the various purposes for employing these Technologies. For a detailed breakdown of all the Technologies we employ, their intended purposes, and specific functionalities, please consult our technologies list. This list undergoes regular updates to furnish you with a precise overview of the Technologies we utilize.";

export const functional1 = "We employ various Technologies to ensure the seamless functionality and user-friendliness of our website. Among these, scripts and cookies play vital roles. Scripts enable interactivity on the website, ensuring that actions such as clicking on elements yield the expected outcomes. Cookies, on the other hand, facilitate essential functions like maintaining the shopping basket and remembering selected products or user addresses. Without cookies, these functions would be impractical.";
export const functional2 = "Certain Technologies used for functional purposes are indispensable to the website's operation and cannot be disabled. These Technologies are retained for a limited duration, typically not exceeding a few hours after your visit to the website. This ensures that critical functionalities remain intact and accessible during your browsing session.";

export const analytical = "We utilize cookies and trackers to analyze your behavior on our website, aiming to enhance and tailor it according to your preferences. By scrutinizing this data, we endeavor to optimize the user-friendliness of our website. For instance, we monitor which pages are most frequently visited and observe how you navigate through our website. This analytical approach enables us to make informed adjustments and improvements, ultimately striving to provide you with the best possible browsing experience.";

export const marketing = "Obviously we hope that you use our website as often as possible and therefore we use cookies and trackers to advertise our website to you. By means of cookies we can offer interesting offers and / or discounts for you. For this purpose we analyze, among other things, how often you use our website and which products you find interesting. This allows us to better adapt our offer and advertisements to your wishes. Another marketing goal for which we use trackers is to check whether you come from a website of one of our advertisers. This is necessary because we have to pay our advertisers for the customers who visit our website via their platform (or places an order on our platform).";

export const security = "Security of your data by Guardos.eu";

export const securityTxt = "Guardos.eu prioritizes the safeguarding of your data and implements suitable measures to prevent its misuse, loss, unauthorized access, inadvertent disclosure, and unauthorized alteration. If you suspect that your data is not adequately secured or if there are any signs of misuse, please do not hesitate to contact us at: guardos-help@outlook.com. Your concerns will be addressed promptly and thoroughly as we are committed to ensuring the security and integrity of your information.";

export const securityThirdParty = "As mentioned earlier, we incorporate third-party Technologies to aid us in fulfilling the stated objectives. These third-party entities contribute to achieving the purposes outlined in this statement. We strictly prohibit third parties from utilizing your data for their own purposes or for purposes that deviate from those described in this statement. Guardos.eu enters into processing agreements with third-party entities responsible for deploying Technologies on our website on our behalf. These processing agreements are established to uphold the same standards of security and confidentiality for your data. We maintain accountability for the processing of your personal data by third parties acting on behalf of Guardos.eu. Rest assured, we remain committed to safeguarding your privacy and ensuring the integrity of your data throughout its processing lifecycle.";

export const enableDisable1 = "You have the flexibility to modify your preferences regarding the Technologies utilized on our website, commonly referred to as cookies across the internet. Additionally, you have the option to delete cookies that have already been placed on your device, as cookies are the only Technology that stores data locally.";
export const enableDisable2 = "However, please note that disabling certain Technologies may result in certain parts of our website no longer functioning properly. It's important to understand that essential Technologies necessary for the operation of the website, which may include some scripts and cookies, cannot be deactivated.";
export const enableDisable3 = "To assist you in adjusting your settings and potentially deleting cookies, we provide links below that guide you through the process for each browser:"; // link different browser instructions (Chrome, Firefox, Edge, Safari)

export const inspect = "You retain the right to request access to, correction, or deletion of your data. For detailed information regarding this process, please refer to our ";
export const inspect2 = ". To prevent misuse, we may request proper identification from you when handling such requests. This measure ensures the security and integrity of your data throughout the process. We are committed to facilitating your rights regarding your personal data in a transparent and responsible manner.";

export const tips = "For comprehensive details regarding our privacy policy and the processing of your personal data, we encourage you to consult our ";
export const tips2 = ". Should you have any inquiries or concerns regarding our cookie policy, we are more than willing to assist you. Your satisfaction and understanding are paramount to us, and we are committed to addressing any questions or complaints you may have regarding our policies. Please feel free to reach out to us for assistance.";

export const conclusion1 = "We may periodically update this cookie statement in response to evolving legal, technical, or business developments. We reserve the right to modify the content of the cookie statement and the cookies listed in the technology list as necessary. Any changes made to the cookie statement will be effective upon posting.";
export const conclusion2 = "If you do not agree with the revised statement, you have the option to adjust your preferences or discontinue using our websites and applications. By continuing to access or utilize our services after the changes take effect, you indicate your acceptance of the revised cookie statement.";
export const conclusion3 = "If you have any further questions or comments, please don't hesitate to contact us via guardos-help@outlook.com or through our privacy form.";
export const conclusion4 = "We encourage you to check back periodically for the latest updates. Previous versions of our cookie statement will be archived for your reference.";
export const conclusion5 = "This cookie statement is subject to modification and was last updated on 08/04/2024.";