version: '3'
services:
  wholeproject:
    build: ./
    ports:
      - "8081:8081"
      - "8080:8080"
      - "8082:8082"
    volumes:
      - ./packages:/app/packages

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

  cadvisor:
    image: google/cadvisor:latest
    ports:
      - "8083:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /sys/fs/cgroup/cpu:/sys/fs/cgroup/cpu:ro
    depends_on:
      - wholeproject
      - prometheus
      - grafana

volumes:
  grafana-storage:
